# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release Deployment Pipeline

on:
  pull_request:
    types: [ closed ]
    branches:
      - release

# Set environment variables
env:

  # notes for applications properties (update pom.xml with these values and update both notes & pom.xml when change is needed):
  # <app.runtime>: 4.4.0                  # Please keep runtime updated to the latest
  # <mule.maven.plugin.version>: 3.3.5    # please keep plugin updated to the latest

  # remember to update constant value of the following properties in pom.xml:
  # <artifactId>, <groupId>, <version>

  #
  # Core pom.xml Properties (Required - These values must match pom.xml - DO NOT replace pom.xml with these variables)
                                                                       # Application Project name

  # Common Properties for all deployment targets
  anypointPlatformBaseUri: https://anypoint.mulesoft.com/                                    # always https://anypoint.mulesoft.com/
  workflowEnv: uat                                                                            # this maps to mule application {env} properties
  applicationName:  "cloudhub-github-actions-api-uat"                                    # Application Name in Runtime Manager
  muleVersion: 4.4.0                                                                          # Mule Version to be deployed - maps to app.runtime
  anypointPlatformUsername: ${{ secrets.anypoint_username }}                         # Anypoint Platform Identity Username for deployment
  anypointPlatformPassword: ${{ secrets.anypoint_password}}                          # Anypoint Platform Identity Password for deployment
  anypointPlatformEnvName: UAT                                                       # Environment name of the deployment target environment (Case Sensitive)
  anypointPlatformBusinessGroup: "DevOps"                                            # The runtime Business Group (Default: master org)
  businessGroupId: b0e42eef-9d72-4a0e-937b-5add27666d99                           # Businessgroup ID from Anypoint platform
  anypointPlatformClientId: ${{ secrets.anypoint_platform_client_id }}                    # Cloudhub Environment Client ID
  anypointPlatformClientSecret: ${{ secrets.anypoint_platform_client_secret }}            # Cloudhub Environment Client Secret
  deploymentTimeout: 1000000                                                                  # deployment timeout setting
  region: us-east-1                                                       # standard naming convention 
  deploymentTarget: "CloudHub"                                                                     
  workers: 1                                                                          #Number of workers
  workerType: Micro                                                                    # Size of worker - MICRO (default; 0.1 vCores). Other Size of worker below requires approval
                                                                             #  SMALL (0.2 vCores)
                                                                             #  MEDIUM (1 vCore )
                                                                             #  LARGE (2 vCores)
                                                                             #  XLARGE (4 vCores)
                                                                             #  XXLARGE (8 vCores)
                                                                             #  4XLARGE (16 vCores)
  objectStoreV2: "false"                                                                            # Please provide the value as true or false based on object store usage in your application  
  anypointPlatformBaseUriProperty: "anypointPlatformBaseUri"                                  # Name of the property that contains the Anypoint Base URI
  muleVersionProperty: "muleVersion"                                                          # Name of the property that contains the MuleSoft runtime version
  usernameProperty: "username"                                                                # Name of the property that contains the Anypoint deployment username
  passwordProperty: "password"                                                                # Name of the property that contains the Anypoint deployment password
  anypointPlatformEnvProperty: "anypoint_platform_env"                                        # Name of the property that contains the Anypoint environment
  businessGroupIdProperty: "businessGroupId"                                                  # Name of the property that contains the Anypoint Business Group Id
  anypointPlatformBusinessGroupProperty: "anypoint_platform_business_group"                   # Name of the property that contains the Anypoint Business Group Name
  applicationNameProperty: "applicationName"                                                  # Name of the property that contains the application name
  envProperty: "env"                                                                          # Name of the property that selects the appropriate config files
  anypointPlatformClientIdProperty: "anypoint_platform_client_id"                             # Name of the property that contains the Anypoint Platform Client Id
  anypointPlatformClientSecretProperty: "anypoint_platform_client_secret"                     # Name of the property that contains the Anypoint Platform Client Secret
  deploymentRegionProperty: "region"                                                                    # Name of the property that contains the region e.g. use1
  deploymentTimeoutProperty: "deploymentTimeout"                                              # Name of the property that contains the Deployment timeout value
  workersProperty: "workers"                                                                  # Name of the property that contains the number of the workers
  workerTypeProperty: "workerType"                                                            # Name of the property that contains the size of the worker


# **************************************** DO NOT MAKE ANY CHANGES TO THIS SCRIPT BELOW THIS POINT ****************************************************
jobs:
  Build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 version
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        #path: ~/.m2/repository
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Create maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v9
      with:
        servers: '[
          {
            "id": "anypoint-exchange-v2", 
            "username": "${{ secrets.anypoint_username }}", 
            "password": "${{ secrets.anypoint_password}}" 
          },
          {
            "id": "github", 
            "username": "${{secrets.githubusername}}", 
            "password": "${{secrets.githubtoken}}" 
          }
        ]'
        repositories: '[
          {
            "id": "MuleRepository", 
            "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/"
            },
          {
            "id": "anypoint-exchange-v2", 
            "url": "https://maven.anypoint.mulesoft.com/api/v2/maven"
            }
        ]'

    - run: |
        cat ~/.m2/settings.xml
    - name: Deploy to ${{ env.deploymentTarget }} 
      run: |
          mvn clean deploy -DskipMunitTests -DmuleDeploy \
          -D${{ env.anypointPlatformBaseUriProperty }}=${{ env.anypointPlatformBaseUri }} \
          -D${{ env.muleVersionProperty }}=${{ env.muleVersion }} \
          -D${{ env.deploymentRegionProperty }}=${{ env.region }} \
          "-D${{ env.usernameProperty }}=${{ env.anypointPlatformUsername }}" \
          "-D${{ env.passwordProperty }}=${{ env.anypointPlatformPassword }}" \
          -D${{ env.workersProperty }}=${{ env.workers }} \
          -D${{ env.workerTypeProperty }}=${{ env.workerType }} \
          -D${{ env.anypointPlatformEnvProperty }}=${{ env.anypointPlatformEnvName }} \
          -D${{ env.businessgroupIdProperty }}=${{ env.businessGroupId }} \
          "-D${{ env.anypointPlatformBusinessGroupProperty }}=${{ env.anypointPlatformBusinessGroup }}" \
          -D${{ env.applicationNameProperty }}=${{ env.applicationName }} \
          -D${{ env.envProperty }}=${{ env.workflowEnv }} \
          -D${{ env.anypointPlatformClientIdProperty }}=${{ env.anypointPlatformClientId }} \
          -D${{ env.anypointPlatformClientSecretProperty }}=${{ env.anypointPlatformClientSecret }} \
          -D${{ env.deploymentTimeoutProperty }}=${{ env.deploymentTimeout }} \
